version: '3.3'

services:
  master:
    build: ./spark
    image: log8430/spark
    container_name: master
    ports:
      - "8080:8080"
      - "7077:7077" 
      - "8888:8888" 
      - "8081:8081"
    command: ["/usr/bin/supervisord", "--configuration=/opt/conf/master.conf"]
  slave:
    build: ./spark
    depends_on:
      - master
    command: ["/usr/bin/supervisord", "--configuration=/opt/conf/slave.conf"]
  driver:
    build: ./spark-driver
    container_name: driver
    depends_on:
      - master
  db:
    build: ./mongo
    volumes:
      - mongo:/data/db
    ports:
      - 27017
  web:
    build: ./web
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  mongo: